apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-vnc
  labels:
    app: vnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc
  template:
    metadata:
      labels:
        app: vnc
    spec:
      containers:
      - name: headless-vnc
        image: promiseuche/glint:chrome-vncserver-0.01
        ports:
        - containerPort: 5900

---

apiVersion: v1
kind: Service
metadata:
  name: headless-vnc
spec:
  selector:
    app: vnc
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5900
